### ISSUE TITLE
Stranica "Adjectives" imaje pogrěšku.

### ISSUE THREAD

**Issue by rzru** [medzuslovjansky/medzuslovjansky.github.io#37]
Pozdrav! 

Stranica "Adjectives" imaje pogrěšku.

Kogda odkryvaju https://interslavic.fun/learn/grammar/adjectives/#inflection vidžu:

```
The basic endings (applying not only to adjectives, but also to possessive pronouns, demonstrative pronouns and the like) are:

<!-- TODO Not working: "import BasicEndings from './partials/_basic-endings.mdx'"; -->

Example of the declension of hard adjectives: dobry „good”:

<!-- TODO Not working: "import AdjectivesGood from './partials/_adjectives-good.mdx'"; -->

Example of the declension of soft adjectives: svěži „fresh”:

<!-- TODO Not working: "import AdjectivesFresh from './partials/_adjectives-fresh.mdx'"; -->
```

**Comment by noomorph** [comment]
@rzru gotovo, ale ješče čekajemo ulěpšenja komponentov mnogo skoro v budučnosti. Vo vsakom slučaju, tehnično tutoj problem jego už nema.

![image](https://github.com/medzuslovjansky/medzuslovjansky.github.io/assets/1962469/a9d6d363-7af4-4d5a-bb8f-c0da029eb290)
